<?php
namespace Modules\Guide\Controllers;

use App\Http\Controllers\Controller;
use Modules\Guide\Models\Guide;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use DB;

class GuideController extends Controller
{
    protected $guideClass;
    protected $locationClass;
    public function __construct()
    {
        $this->guideClass = Guide::class;
        $this->locationClass = Location::class;
    }
    public function callAction($method, $parameters)
    {
        if(!Guide::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        
        $is_ajax = $request->query('_ajax');
        
        $model_guide = $this->guideClass::select("bravo_guides.*");
        $model_guide->where("bravo_guides.status", "publish");
        if (!empty($location_id = $request->query('location_id'))) {
            $location = $this->locationClass::where('id', $location_id)->where("status","publish")->first();
            if(!empty($location)){
                $model_guide->join('bravo_locations', function ($join) use ($location) {
                    $join->on('bravo_locations.id', '=', 'bravo_guides.location_id')
                        ->where('bravo_locations._lft', '>=', $location->_lft)
                        ->where('bravo_locations._rgt', '<=', $location->_rgt);
                });
            }
        }
        if (!empty($price_range = $request->query('price_range'))) {
            $pri_from = explode(";", $price_range)[0];
            $pri_to = explode(";", $price_range)[1];
            $raw_sql_min_max = "(  bravo_guides.price >= ? ) 
                            AND (  bravo_guides.price <= ? )";
            $model_guide->WhereRaw($raw_sql_min_max,[$pri_from,$pri_to]);
        }
        if (!empty($min_age = $request->query('min_age')) 
                && 
                !empty($max_age = $request->query('max_age'))) {
            $min_year = date('Y')-$min_age;
            $max_year =  date('Y')-$max_age;
            
            $raw_sql_min_max = "(  year(bravo_guides.dob) >= ? ) 
                            AND (  year(bravo_guides.dob) <= ? )";
            $model_guide->WhereRaw($raw_sql_min_max,[$max_year,$min_year]);
            
        }
        if (!empty($star_rate = $request->query('star_rate'))) {
            $model_guide->WhereIn('star_rate',$star_rate);
        }

        $terms = $request->query('terms');
        if($term_id = $request->query('term_id'))
        {
            $terms[] = $term_id;
        }
        if (is_array($terms) && !empty($terms)) {
            $model_guide->join('bravo_guide_term as tt', 'tt.target_id', "bravo_guides.id")->whereIn('tt.term_id', $terms);
        }

        $review_scores = $request->query('review_score');
        if (is_array($review_scores) && !empty($review_scores)) {
            $where_review_score = [];
            foreach ($review_scores as $number){
                $where_review_score[] = " ( bravo_guides.review_score >= {$number} AND bravo_guides.review_score <= {$number}.9 ) ";
            }
            $sql_where_review_score = " ( " . implode("OR", $where_review_score) . " )  ";
            $model_guide->WhereRaw($sql_where_review_score);
        }

        $model_guide->orderBy("id", "desc");
        $model_guide->groupBy("bravo_guides.id");

        $list = $model_guide->with(['location','hasWishList','translations','termsByAttributeInListingPage'])->paginate(9);
        $markers = [];
        if (!empty($list)) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Guide::frontend.layouts.search.loop-grid', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker'  => url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if( empty(setting_item("guide_location_search_style")) or setting_item("guide_location_search_style") == "normal" ){
            $limit_location = 1000;
        }
        
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translations'])->get()->toTree(),
            'guide_min_max_price' => $this->guideClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank"              => 1,
            "seo_meta"           => $this->guideClass::getSeoMetaForPageList()
        ];
        $layout = setting_item("guide_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        if ($is_ajax) {
            $this->sendSuccess([
                'html'    => view('Guide::frontend.layouts.search-map.list-item', $data)->render(),
                "markers" => $data['markers']
            ]);
        }
        $data['attributes'] = Attributes::where('service', 'guide')->with(['terms','translations'])->get();

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Guide::frontend.search-map', $data);
        }        
        return view('Guide::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->guideClass::where('slug', $slug)->where("status", "publish")->with(['location','translations','hasWishList'])->first();;
        if (empty($row)) {
            return redirect('/');
        }
        $translation = $row->translateOrOrigin(app()->getLocale());
        $guide_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $guide_related = $this->guideClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location','translations','hasWishList'])->get();
        }
        $review_list = Review::where('object_id', $row->id)->where('object_model', 'guide')->where("status", "approved")->orderBy("id", "desc")->with('author')->paginate(setting_item('guide_review_number_per_page', 5));
        $data = [
            'row'          => $row,
            'translation'       => $translation,
            'guide_related' => $guide_related,
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single'
        ];
        $this->setActiveMenu($row);
        return view('Guide::frontend.detail', $data);
    }

    public function checkAvailability(){
        $guide_id = \request('guide_id');

        if(!\request()->input('firstLoad')) {
            request()->validate([
                'guide_id'   => 'required',
                'start_date' => 'required:date_format:Y-m-d',
                'end_date'   => 'required:date_format:Y-m-d',
            ]);

            if(strtotime(\request('end_date')) - strtotime(\request('start_date')) < DAY_IN_SECONDS){
                $this->sendError(__("Dates are not valid"));
            }
            if(strtotime(\request('end_date')) - strtotime(\request('start_date')) > 30*DAY_IN_SECONDS){
                $this->sendError(__("Maximum day for booking is 30"));
            }
        }

        $guide = $this->guideClass::find($guide_id);
        if(empty($guide_id) or empty($guide)){
            $this->sendError(__("Guide not found"));
        }

        $rooms = $guide->getGuideAvailability(request()->input());

        $this->sendSuccess([
            'rooms'=>$rooms
        ]);
    }
}
