<?php
namespace Modules\Activity\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Activity\Models\Activity;
use Modules\Activity\Models\ActivityDate;
use Modules\Activity\Models\ActivityBooking;

class AvailabilityController extends FrontendController{

    /**
     * @var ActivityDate
     */
    
    protected $activityClass;
    protected $activityDateClass;

    /**
     * @var Booking
     */
    protected $bookingClass;
    protected $currentActivity;
    protected $activityBookingClass;
    protected $indexView = 'Activity::frontend.user.availability';

    public function __construct()
    {
        parent::__construct();
        $this->activityDateClass = ActivityDate::class;
        $this->bookingClass = Booking::class;
        $this->activityClass = Activity::class;
        $this->activityBookingClass = ActivityBooking::class;
    }
    public function callAction($method, $parameters)
    {
        if(!Activity::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    protected function hasActivityPermission($activity_id = false){
        if(empty($activity_id)) return false;

        $activity = $this->activityClass::find($activity_id);
        if(empty($activity)) return false;

        if(!$this->hasPermission('activity_update') and $activity->create_user != Auth::id()){
            return false;
        }

        $this->currentActivity = $activity;
        return true;
    }

    public function index(Request $request,$activity_id){

        $this->checkPermission('activity_create');

        if(!$this->hasActivityPermission($activity_id))
        {
            abort(403);
        }
        $q = $this->activityClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        $q->orderBy('id','desc');
        $q->where('id',$activity_id);

        $rows = $q->paginate(15);
        
        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Activitys'),
                'url'  => route('activity.vendor.index')
            ],
            [
                'name' => __('Activity: :name',['name'=>$this->currentActivity->title]),
                'url'  => route('activity.vendor.edit',[$this->currentActivity->id])
            ],
            [
                'name'  => __('Availability'),
                'class' => 'active'
            ],
        ];
        $activity = $this->currentActivity;
        $page_title = __('Activity Availability');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request','activity'));
    }

    public function loadDates(Request $request,$activity_id){

        $request->validate([
            'id'=>'required',
            'start'=>'required',
            'end'=>'required',
        ]);

        if(!$this->hasActivityPermission($activity_id))
        {
            $this->sendError(__("Activity not found"));
        }
        /**
         * @var $activity ActivityActivity
         */

        $activity = $this->activityClass::find($request->query('id'));
        if(empty($activity)){
            $this->sendError(__('activity not found'));
        }

        $is_single = $request->query('for_single');
        $query = $this->activityDateClass::query();
        $query->where('target_id',$request->query('id'));
        $query->where('start_date','>=',date('Y-m-d H:i:s',strtotime($request->query('start'))));
        $query->where('end_date','<=',date('Y-m-d H:i:s',strtotime($request->query('end'))));

        $rows =  $query->take(40)->get();
        $allDates = [];

        for($i = strtotime($request->query('start')); $i <= strtotime($request->query('end')); $i+= DAY_IN_SECONDS)
        {
            $date = [
                'id'=>rand(0,999),
                'active'=>0,
                'price'=> $activity->price,
                'number'=> $activity->number,
                'is_instant'=>0,
                'is_default'=>true,
                'textColor'=>'#2791fe'
            ];
            $date['price_html'] = format_money($date['price']);
            if(!$is_single){
                $date['price_html'] = format_money_main($date['price']);
            }
            $date['title'] = $date['event']  = $date['price_html'];
            $date['start'] = $date['end'] = date('Y-m-d',$i);

            $date['active'] = 1;
            $allDates[date('Y-m-d',$i)] = $date;
        }
        if(!empty($rows))
        {
            foreach ($rows as $row)
            {
                $row->start = date('Y-m-d',strtotime($row->start_date));
                $row->end = date('Y-m-d',strtotime($row->start_date));
                $row->textColor = '#2791fe';
                $price = $row->price;
                if(empty($price)){
                    $price = $activity->price;
                }
                $row->title = $row->event = format_money($price);
                if(!$is_single){
                    $row->title = $row->event = format_money_main($price);
                }
                $row->price = $price;

                if(!$row->active)
                {
                    $row->title = $row->event = __('Blocked');
                    $row->backgroundColor = '#fe2727';
                    $row->classNames = ['blocked-event'];
                    $row->textColor = '#fe2727';
                    $row->active = 0;
                }else{
                    $row->classNames = ['active-event'];
                    $row->active = 1;
//                    if($row->is_instant){
//                        $row->title = '<i class="fa fa-bolt"></i> '.$row->title;
//                    }
                }

                $allDates[date('Y-m-d',strtotime($row->start_date))] = $row->toArray();

            }
        }
        $bookings = $activity->getBookingsInRange($request->query('start'),$request->query('end'));
        if(!empty($bookings))
        {
            foreach ($bookings as $booking){
                for($i = strtotime($booking->start_date); $i <= strtotime($booking->end_date); $i+= DAY_IN_SECONDS){
                    if(isset($allDates[date('Y-m-d',$i)])){
                        $allDates[date('Y-m-d',$i)]['number'] -= $booking->number;

                        if($allDates[date('Y-m-d',$i)]['number'] <=0 ){
                            $allDates[date('Y-m-d',$i)]['active'] = 0;
                            $allDates[date('Y-m-d',$i)]['event'] = __('Full Book');
                            $allDates[date('Y-m-d',$i)]['title'] = __('Full Book');
                            $allDates[date('Y-m-d',$i)]['classNames'] = ['full-book-event'];
                        }
                    }
                }
            }
        }

        $data = array_values($allDates);

        return response()->json($data);
    }

    public function store(Request $request,$activity_id){

        if(!$this->hasActivityPermission($activity_id))
        {
            $this->sendError(__("Activity not found"));
        }

        $request->validate([
            'target_id'=>'required',
            'start_date'=>'required',
            'end_date'=>'required',
            'price'=>'required'
        ]);

        $activity = $this->activityClass::find($request->input('target_id'));
        $target_id = $request->input('target_id');

        if(empty($activity)){
            $this->sendError(__('Activity not found'));
        }

        if(!$this->hasPermission('activity_manage_others')){

            if($this->currentActivity->create_user != Auth::id()){
                $this->sendError("You do not have permission to access it");
            }
        }

        $postData = $request->input();
        for($i = strtotime($request->input('start_date')); $i <= strtotime($request->input('end_date')); $i+= DAY_IN_SECONDS)
        {
            $date = $this->activityDateClass::where('start_date',date('Y-m-d',$i))->where('target_id',$target_id)->first();

            if(empty($date)){
                $date = new $this->activityDateClass();
                $date->target_id = $target_id;
            }
            $postData['start_date'] = date('Y-m-d H:i:s',$i);
            $postData['end_date'] = date('Y-m-d H:i:s',$i);


            $date->fillByAttr([
                'start_date','end_date','price',
                'is_instant','active',
                'number'
            ],$postData);

            $date->save();
        }

        $this->sendSuccess([],__("Update Success"));

    }
}
